#pragma once

#ifndef AZDECK_MAX_CHANNELS
#define AZDECK_MAX_CHANNELS 32
#endif

#ifndef AZDECK_MAX_CHANNEL_NAME_LENGTH
#define AZDECK_MAX_CHANNEL_NAME_LENGTH 32
#endif

#ifndef AZDECK_RX_BUFFER_SIZE
#if defined(ARDUINO) && (defined(ARDUINO_UNOR4_WIFI) || defined(ESP8266))
#define AZDECK_RX_BUFFER_SIZE 512
#else
#define AZDECK_RX_BUFFER_SIZE 1024
#endif
#endif

#ifndef AZDECK_JSON_DOC_SIZE
#if defined(ARDUINO) && (defined(ARDUINO_UNOR4_WIFI) || defined(ESP8266))
#define AZDECK_JSON_DOC_SIZE 768
#else
#define AZDECK_JSON_DOC_SIZE 1024
#endif
#endif

#ifndef AZDECK_PACKET_QUEUE_DEPTH
#define AZDECK_PACKET_QUEUE_DEPTH 4
#endif

#ifndef AZDECK_MAX_DEVICE_NAME_LENGTH
#define AZDECK_MAX_DEVICE_NAME_LENGTH 31
#endif

#ifndef AZDECK_MAX_SSID_LENGTH
#define AZDECK_MAX_SSID_LENGTH 32
#endif

#ifndef AZDECK_MAX_PASSWORD_LENGTH
#define AZDECK_MAX_PASSWORD_LENGTH 64
#endif

#define AZDECK_DEFAULT_NAME "AzDeck"
#define AZDECK_DEFAULT_SSID "AzDeck"
#define AZDECK_DEFAULT_PASSWORD "azdeck123"
#define AZDECK_DEFAULT_WS_PORT 81
#define AZDECK_DEFAULT_TCP_PORT 5000
#define AZDECK_DEFAULT_TIMEOUT_MS 350
